version: "3.5"

services:
  database:
    image: postgres:10
    container_name: postgres-10
    hostname: postgres-10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres:
